### ISSUE TITLE
Any plans for stable release

### ISSUE THREAD

**Issue by ivankravets** [pavlov99/ajsonrpc#2]
Hi,

Thanks for the useful package! We use it for @platformio.

Do you have any plan to complete work on https://github.com/pavlov99/ajsonrpc/blob/master/ajsonrpc/manager.py and publish a stable release?

P.S: We currently use https://github.com/pavlov99/json-rpc with async wrappers. It would be great to use the official version.

**Comment by pavlov99** [comment]
Hi @ivankravets

I paused work on this as did not see a lot of interest in the past. I'm happy to update this and publish a stable release! I'm hoping to do so during the next week.

Thank you for sharing your project! What python version are you developing in?

**Comment by ivankravets** [comment]
We support Python 3.6+. You can check a few workarounds that we made for JSON-RPC to make it compatible with asyncio:
- https://github.com/platformio/platformio-core/blob/develop/platformio/commands/home/rpc/server.py#L97

**Comment by pavlov99** [comment]
Hi @ivankravets 

I released an alpha version [ajsonrpc 1.0.0a0](https://pypi.org/project/ajsonrpc/1.0.0a0/) that should have stable interface. I plan to wait for a couple of weeks for the feedback and possible late stage bug issues, though, I do not expect any significant changes.

Unlike `json-rpc` this version does not include Django/Flask backend support it the latter would lengthen the development. Though, in your case it would not be a blocker as platformio uses manager directly.

 There were some minor changes compared to `json-rpc` and I'm yet to write a migration guide. In general, serialization/deserialization logic was moved from primitives (request, response, etc.) to manager. More handling methods were added, depending on desired level of control. The rest should be largely the same.

Please let me know if it fits your case.

**Comment by ivankravets** [comment]
Sorry for the delay. I've finally switched PlatormIO Core to this package https://github.com/platformio/platformio-core/commit/0b8bd6d4fc3570bb3711dbfe35ecedffb8a5ca4e

Great API! Thank you so much for your efforts!

P.S: Is it possible to instruct `AsyncJSONRPCResponseManager` to handle the global exception and pass it to https://github.com/pavlov99/ajsonrpc/blob/master/ajsonrpc/manager.py#L58 ?

For example, `"Server error: %s" % dispatch_error`. I agree that the developer should wrap own code with try/except.  However, it's good to have some flag/option to bypass the exception to the response's error.

**Comment by pavlov99** [comment]
Regarding global exception, could you please provide more context/examples?

The reason it is implemented this way is to prevent information leakage from the server, so if an error is unexpected, ajsonrpc would return a generic error without giving any unwanted information. I think it is possible to have two modes: 1) secure by default and 2) return full error log (if specified in constructor, for example). Would this suit your case?

**Comment by ivankravets** [comment]
> Regarding global exception, could you please provide more context/examples?

The case when "method" raises an unexpected exception.

We report these errors to the user's frontend, and later they report us to the Github issues.

> The reason it is implemented this way is to prevent information leakage from the server, so if an error is unexpected, ajsonrpc would return a generic error without giving any unwanted information.

Yes, the current behavior is correct. No need to change it.

> 2) return full error log (if specified in constructor, for example). Would this suit your case?

Yes, this is what could help us. See the example below. In our case of an open source project, it makes sense for us to show a detailed report. It will help us to investigate the issue.

![Screen Shot 2021-02-28 at 19 22 30](https://user-images.githubusercontent.com/1760209/109427287-4fa60f80-79fa-11eb-8355-ffc26acf9985.png)

**Comment by pavlov99** [comment]
This PR might work: https://github.com/pavlov99/ajsonrpc/pull/18
I'll review it again tomorrow and release the new version.

**Comment by ivankravets** [comment]
PR #18 looks great! Thank you so much! 😊

**Comment by pavlov99** [comment]
I've just released `1.1.0` with the update. Closing this issue.

**Comment by ivankravets** [comment]
Thanks! It works 👍 

![Screen Shot 2021-03-01 at 17 54 55](https://user-images.githubusercontent.com/1760209/109522765-49c23400-7ab7-11eb-816a-e18dc3fcbade.png)
